### ISSUE TITLE
Pretrained model on GTA<->BDD

### ISSUE THREAD

**Issue by pkyong95** [charliememory/EGSC-IT#1]
First, thank you for great work and releasing valuable codes.

Now, I'm trying to test pre-trained model on GTA<->BDD, however I fail to load it.
Other pre-trained models (MNIST, MNIST_multi, CelebA) are successfully loaded.

The noticeable difference between them are that zip file for other dataset contains two folders(Model0, Model1), but zip file for GTA<->BDD contains only one folder(Model0).

Can you double-check the pre-trained model on GTA<->BDD?

**Comment by charliememory** [comment]
Sorry for the late reply. The pre-trained model file is corrupted. Now I retrained a new one to replace the old one. And I also upgrade the code to python3 version.
