### ISSUE TITLE
sggan not defined.

### ISSUE THREAD

**Issue by hi-zhengcheng** [charliememory/EGSC-IT#2]
https://github.com/charliememory/EGSC-IT/blob/6ab8bd3f8163963f3be703251b3850b0b2f4ec80/main.py#L119

@charliememory it seems that `sggan` is not defined in any files. Are there missing files or updates not submitted ? If this code is just for test, maybe you can delete it.

**Comment by charliememory** [comment]
They are some dummy code for test and I just removed them for clarity. Thanks for your feedback.
